services:
  cli:
    image: php:8.2.24-cli
    command: ["sleep", "infinity"]
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    volumes:
      - ./src:/var/www/html
    ports:
      - 8080:80
    depends_on: 
      - php
  php:
    build:
      context: ./php-fpm
      dockerfile: Dockerfile
    volumes:
      - ./src:/var/www/html
  postgres:
    image: postgres:16.4-alpine3.20
    volumes:
      - ./docker/entrypoint-initdb.d:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_PASSWORD=password
    ports:
      - 5432:5432